export default {
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 16,
  FONT_SIZE_LARGE: 18,
  FONT_SIZE_HEADING: 25,
  PRIMARY_COLOR: '#6DDA71',
  SECONDARY_COLOR: '#A6E182',
  TERTIARY_COLOR: '#DBF9C9',
  ICON_SIZE_SMALL: 30,
  ICON_SIZE_MEDIUM: 45,
  ICON_SIZE_LARGE: 60,
};
